apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: secret-detection-pipelinerun
spec:
  pipelineRef:
    name: secret-detection-pipeline
  workspaces:
  - name: workspace
    persistentvolumeclaim:
      claimName: pvc