apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secret-detection-pipeline
spec:
  workspaces:
  - name: workspace
  tasks:
  - name: secret-detection
    taskRef: 
      name : secret-detection
    workspaces:
      - name: source
        workspace: workspace
    params:
    - name: repo_url
      value: https://github.com/urvashigupta7/contest-arena
    - name: clone_path
      value: contest-arena
    - name: config_file_url
      value: https://raw.githubusercontent.com/urvashigupta7/secret_detection/master/gitleaks.toml
    - name: config_file_path
      value: gitleaks.toml
    - name: output_format
      value: json
    - name: report_output_path
      value: report.json