apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: secret_detection_pipeline
spec:
  params: 
    - name: repository
      type: string
  workspaces:
  - name: workspace
  tasks:
  - name: detect_secret
    taskRef: 
      name : detect-secret
    workspaces:
      - name: source
        workspace: workspace
    params:
    - name: repo_url
      value: https://github.com/urvashigupta7/contest-arena
    - name: clone_path
      value: contest-arena
    - name: config_file_url
      value: 
    - name: config_file_path
      value: gitleaks.toml
    - name: output_format
      value: json
    - name: report_output_path
      value: report.json