apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: secret-detection-pipelinerun
spec:
  pipelineRef:
    name: secret-detection-pipeline
  params:
  - name: repo_url
    value: https://github.com/urvashigupta7/contest-arena
  - name: repo_path
    value: contest-arena
  workspaces:
  - name: workspace
    persistentvolumeclaim:
      claimName: pvc