apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: secret_detection_pipelinerun
spec:
  pipelineRef:
    name: secret_detection_pipeline
  workspaces:
  - name: workspace
    persistentvolumeclaim:
      claimName: pvc